new one bc git messed up
Bwalker01/acme pull request #11
Opened 2023-07-26 11:25 UTC by MattyHoughton

2023-07-26 11:57 UTC, Bwalker01 commented on .vs/acme/config/applicationhost.config
haven't used visual studio but im presuming that's where this .vs folder has come from, should this not be included in a .gitignore to prevent it from pushing or is it required for general use of the webpage?

2023-07-26 11:59 UTC, Bwalker01 requested changes
mostly looks good, just want to know about adding the .vs folder and whether its necessary in the codebase.

2023-07-26 12:25 UTC, MattyHoughton commented on .vs/acme/config/applicationhost.config
I don't think it's required as it's just the local IDE files, will add it to the .gitignore

2023-07-27 13:09 UTC, closed without merging

2023-07-27 13:13 UTC, Bwalker01 reviewed
LGTM 👍